using System;
using System.Linq;

namespace Mastermind
{
    class Program
    {
        static char[] guessedArray;
        static void Main(string[] args)
        {
            PlayMastermind();

        }
        public static void PlayMastermind()
        {
            Console.WriteLine("This is a game you are asked to guess a random 4 digit number generated by computer between 1 and 6" +
                " You are give 10 chances to guess the number" +
                " Your guessed number is matched by digit position." +
                " After the player enters a combination, a minus (-) sign should be printed for every digit that is correct but in the wrong position, " +
                "and a plus (+) sign should be printed for every digit that is both correct and in the correct position. " +
                " Nothing should be printed for incorrect digits.  " +
                "The player has ten (10) attempts to guess the number correctly before receiving a message that they have lost.");
            string random = RandomNumber();
            char[] num = random.ToCharArray();
            string guess;
            
            //This loop runs 10 times
            for (int j = 0; j < 11; j++)
            {
                Console.WriteLine("Please Enter a 4 digit number between 1 and 6. ");
                guess = Console.ReadLine();
                guessedArray = guess.ToCharArray();
                string nearmatch = "";
                //If the user enters a number less than 4 digit length then user is asked to enter proper 4 digit numbers
                if (guess.Length != 4 )
                {
                    Console.WriteLine("You have not entered 4 digit number between 1 and 6");
                }
                else if(guess.Length == 4)
                {
                    if (iseachdigitvalid())
                    {
                        Console.WriteLine("Each digit number is not between 1 and 6");

                    }
                    else
                    {
                        for (var i = 0; i < random.Length; i++)
                        {

                            if (guessedArray[i] == num[i])
                            {
                                guessedArray[i] = '+';
                            }
                            else if (random.Contains(guessedArray[i]))
                            {
                                guessedArray[i] = '-';
                            }
                            else
                            {
                                guessedArray[i] = ' ';
                            }
                            nearmatch += guessedArray[i];
                        }
                        Console.WriteLine("your guess is:" + "{0}", nearmatch);
                        if (j == 10)
                        {
                            Console.WriteLine("random number is {0}", random);
                        }

                        if (guess == random)
                        {
                            Console.WriteLine("You won, random number is {0}", random);
                            break;
                        }
                        else
                        {
                            Console.WriteLine("you lost");
                        }
                    }
                }

            }  
        }
        //This function checks if each digit is between 1 and 6
        public static bool iseachdigitvalid()
        {
            bool b = false;
            foreach (var guess in guessedArray)
            {
                int g = Convert.ToInt16(guess);
                if ( g < 49 || g > 54)
                {
                    b = true;
                    break;
                }
            }
            return b;
        }
        public static string RandomNumber()
        {
            //generation random 4 digit numbers between 1 and 6
            var chars = "123456";
            var random = new Random();
            var result = new string(Enumerable.Repeat(chars, 4).Select(s => s[random.Next(s.Length)]).ToArray());
            string number = result.ToString();
            return number;
        }
    }
}
